version: '3'
services:
  postgres:
    build:
      context: docker/postgres
      dockerfile: Dockerfile
    command: >
      -c ssl=on 
      -c ssl_cert_file=/var/lib/postgresql/server.crt 
      -c ssl_key_file=/var/lib/postgresql/server.key
    ports:
      - 5432:5432